### ISSUE TITLE
Delayed Evaluation

### ISSUE THREAD

**Issue by perfectmak** [shalvah/aargh#2]
I like the interface `aargh` exposes for handling errors.

What I'm proposing is a syntax where `others()` or `throw()` returns a function if `aargh()` was invoked without an error. So for example:

```javascript
const errorHandler = aargh()
   .type(RateLimitExceededError, (e) => {})
   .others((e) => { // do some other stuffs });

// errorHandler is a function that takes in the error and then evaluates the aargh chain.
// so it can be used later on like
fetchTweets(userId).catch(errorHandler);
```

I currently see this additional feature providing two benefits:

1. Being able to re-use aargh chains defined previously or in another module or external library.
2. 😄 It would be super convenient for people who don't use async/await so often

**Comment by shalvah** [comment]
I see what you're saying. It's a good idea, and I'll consider it, but I don't know if it's worth complicating the API to add a convenience. 

For instance, the same thing can be achieved by doing:

```javascript
const errorHandler = (e) => {
    return aargh(e)
       .type(RateLimitExceededError, (e) => {})
       .others((e) => { });
};

fetchTweets(userId).catch(errorHandler);
```

On "complicating the API": I worry that it will create unnecessary confusion, and be another item in the docs  that users need to understand.

**Comment by perfectmak** [comment]
True, manually wrapping it in a function works too. I was just sharing a possible way the chains could also work. Nice work. 

Please, feel free to close this issue.

**Comment by shalvah** [comment]
Yeah, I think I'll keep it like this for now.
