### ISSUE TITLE
Show import of RateLimitExceedError in documentation

### ISSUE THREAD

**Issue by holuborhee** [shalvah/aargh#3]
Good job on the project 👍.

I noticed something that may be confusing to beginners though, **you used RateLimitExceedError, without showing where you are importing it.** I feel it may be confusing to users who want to use this package and will be using for Exceptions outside the standard JavaScript exceptions. 

A simple line of import will clarify things better.

**Comment by shalvah** [comment]
Hmmm. I see your point. But I won't add any imports or extra code. I don't want to distract from the main functionality. I'll add a note to clarify. Thanks.
